### ISSUE TITLE
mal so als anregung

### ISSUE THREAD

**Issue by michabbb** [phoice/phlexa#2]
servus,

ich würde das framework hier ja gerne benutzen, aber null docu und das skeleton besitzt auch kein howto und zudem ist es nutzlos, wenn man laravel benutzt. von daher werde ich wohl etwas altes benutzen, was aber wenigstens ansatzweise erklärt ist. ich dachte, vielleicht interessiert es dich. ist halt schade wenn jemand etwas public macht aber keiner kanns nutzen. lg

**Comment by RalfEggert** [comment]
@michabbb I hope you don't mind when I answer in English.

First of all, you are absolutely right. The missing documentation is the biggest issue we currently have. There is a small tutorial to get started in the skeleton. But that is no enough.

https://github.com/phoice/phlexa-expressive-skeleton#little-tutorial

Currently, our team is really working with the framework and not for the framework due to lack of time. Our plans are:

- Add documentation for all repos
- Add a tutorial for building Alexa Skills with the Zend\Expressive skeleton
- Support more issues for Alexa requests and responses
- Add more repos to support other frameworks like Symfony, Laravel, ...

For the last point we really need some experts for these frameworks. But the first step would be adding documentation for the repos or at least a tutorial for the Zend\Expressive skeleton.

Really looking forward for people to support us.

**Comment by michabbb** [comment]
i wouldn´t focus on a skeleton, this forces user to use something they don´t want.
i recommand focus on the framework itself (if this project is the framework, i don´t know) - so that everybody is able to use it, doesn´t matter if i use zend, laravel or any other framework. that´s why i have choosen [this](https://github.com/maxbeckers/amazon-alexa-php). here i am not limited or forced to use something i don´t want. a developer builds his own skeleton based on his preferred framework 😏 
so i don´t understand why you are going to build something that needs support for symfony or laravel, a stand-alone alex-php project doesn´t need such bindings or dependencies, in my eyes this is the complete wrong way of building something like this. but hey, it´s your project, i just wanted to leave a comment for the better 😏 thanks for your feedback.

**Comment by RalfEggert** [comment]
Just another addition to clarify: 

- The [phlexa project](https://github.com/phoice/phlexa/) is the core framework.
- The [phlexa-expressive project](https://github.com/phoice/phlexa-expressive] is just an addon for Zend\Expressive users.
- The [phlexa-expressive-skeleton project](https://github.com/phoice/phlexa-expressive-skeleton) is just a Quickstart for Zend\Expressive users

I guess we did not work that out clearly. The core framework needs a lot of framework independent documentation. The other planned skeleton should only work as other Quickstarts but the main phlexa project will definitely be framework independent.

So, my next step would be to write a detailed documentation for this repo.

I really appreciate your feedback and comments which make me think that we still have a long way to go.
